# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Avneesh Sharma"
resume_title:                   "Data Science Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tourist836@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Lucknow, Uttar Pradesh"

resume_header_contact_info:     "Lucknow, Uttar Pradesh • 555-7334 • tourist836@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Amazon AWS Cloud Solutions Architect Associate | Intern Indian Space Research Organisation (ISRO) U R Rao Satellite Center (URSC) Bangalore | AWS Subject Matter Expert (SME) | AWS Certified Global Community Member | Researcher at SPIE (Society of Photographic Instrumentation Engineers) | Campus Ambassador Manipal University Jaipur | Head Of R&D ELECTRONICS SOCIETY Manipal University Jaipur | Intern Defense Research and Development Organisation (DRDO) Solid State Physics Laboratory Delhi | Researcher at Optica PHOTONIC CRYSTAL FIBRE | Google Cloud Computing Engineer | Graphics Designer | Electronics Sub-System Designer Mars Rover Manipal University Jaipur</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Avi836"
  resume_twitter_url:           "https://twitter.com/tourist836"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/avneesh.sharma.50951"
  resume_linkedin_url:          "https://www.linkedin.com/in/avneesh-sharma-profile/"
  resume_instagram_url:         "https://www.instagram.com/tourist836/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
